airlines = ['emirates','air new zealand','delta','qantas','jetstar']
print('This is a list called airlines.')
print(airlines)
print('This is the 4th element (I am including the 0th element).')
print(airlines[4])
print('This is the 4th element beginning with a capital letter.')
print(airlines[4].title())
print(f'The WORST AIRLINE EVER is {airlines[4].title()}')
print("They didn't let me buy any banana bread. :(") 
print('This is the list:')
print(airlines)
print('I have changed delta to singapore airlines.')
airlines[2] = 'singapore airlines'
print(airlines)
print('Now I will add american airlines to the end.')
airlines.append('american airlines')
print(airlines)
print('Next I will add alaska airlines in the 4th position.')
airlines.insert(4,'alaska airlines')
print(airlines)
print('Jetstar will now be deleted! HAHAHAHAAAAA!!!')
del airlines[5]
print(airlines)
print('\tMWAHAHAHAAA')
popped_airline = airlines.pop(3)
print("I just popped qantas from the list.")
print(airlines)
print("I have stored qantas as a variable called popped_airline.")
print(f"Here is popped_airline:  {popped_airline}")
print("I will now remove emirates.")
airlines.remove('emirates')
print(airlines)
print("I will used the sorted() function to temporarily sort airlines into alphabetical order.")
print(sorted(airlines))
print(airlines)
print("I will used the sort() function to permanently sort airlines into alphabetical order.")
airlines.sort()
print(airlines)
print("I will used the sort(reverse=True) function to permanently sort airlines into reverse alphabetical order.")
airlines.sort(reverse=True)
print(airlines)
print("Here is the reversed list.")
airlines.reverse()
print(airlines)
print(f"The length of airlines is {len(airlines)}.")
print(f"The last element of airlines is {airlines[-1]}.")