locations = ['japan','mexico','iceland','uluru','brazil','france']
print(locations)
print('This is the original list. It is called locations.')
print(sorted(locations))
print('This is locations temporarily in alphabetical order.')
print(locations)
print("Locations has been returned to it's original order.")
locations.reverse()
print(locations)
print('Locations has been reversed.')
locations.reverse()
print(locations)
print("Locations has been returned to it's original order.")
locations.sort()
print(locations)
print('Locations is now in alphabetical order.')
locations.sort(reverse=True)
print(locations)
print('Locations is now in reverse alphabetical order.')